platzigram/urls.py
"""
Archivo de URLS de platzigram

"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static  # para poder ver la foto del usuario
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

 
    # Llama a posts/urls.py cuando se entra al home
    path('', include(('posts.urls','posts'), namespace='posts')),

    # Llama a users/urls.py cuando se entra al home/users/...
    path('users/', include(('users.urls', 'users'), namespace='users')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #para mostrar la foto

#https://docs.djangoproject.com/en/2.2/ref/settings/

posts/urls.py
# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

   path(
       route='', 
       view=views.PostsFeedView.as_view(), 
       name='feed'
    ),

   path(
       route='posts/new/', 
       view=views.CreatePostView.as_view(),
       name='create'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
]

users/urls.py
# URLS de usuarios

# Django
from django.urls import path
#https://docs.djangoproject.com/en/2.1/topics/class-based-views/#simple-usage-in-your-urlconf
#https://ccbv.co.uk/

# Views
from users import views

urlpatterns = [

    #Posts
    path(
        route='<str:username>/', #este es el kwarg (key word argument)
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # Administración
    path(
        route='login/', 
        view=views.login_view, 
        name='login'
    ),
    path(
        route='logout/', 
        view=views.logout_view, 
        name='logout'
    ),
    path(
        route='signup/', 
        view=views.signup, 
        name='signup'
    ),
    path(
        route='me/profile/', 
        view=views.update_profile, 
        name='update'
    )

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block head_content %}
    {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>
<body>

    {% include "nav.html" %}

    <div class="container mt-5">
        {% block container %}
        {% endblock%}
    </div>

</body>
</html>

templates/nav.html
{% load static %}
<nav class="navbar navbar-expand-lg fixed-top" id="main-navbar">
    <div class="container">

        <a class="navbar-brand pr-5" style="border-right: 1px solid #efefef;" href="{% url 'posts:feed' %}">
            <img src="{% static "img/instagram.png" %}" height="45" class="d-inline-block align-top"/>
        </a>

        <div class="collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">

                <li class="nav-item">
                    <!-- Para actualizar la foto chiquita del navbar. Si tiene la muestra, sino pone el default-->
                    <a href="{% url "users:detail" request.user.username %}">
                        {% if request.user.profile.picture %}
                        <img src="{{ request.user.profile.picture.url }}" height="35" class="d-inline-block 
                            align-top rounded-circle" />
                        {% else %}
                            <img src="{% static 'img/default-profile.png' %}" height="35" class="d-inline-block 
                            align-top rounded-circle"/>
                        {% endif %}
                    </a>
                </li>

<!-- https://docs.djangoproject.com/en/3.0/topics/auth/default/#auth-web-requests 
recordar configurar las URLS de logout y profile -->
                <li class="nav-item nav-icon">
                    <a href="{% url 'posts:create' %}">
                        <i class="fas fa-plus"></i>
                    </a>
                </li>

                <li class="nav-item nav-icon">
                    <a href="{% url 'users:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/pagination.html
<nav>
    <ul class="paginatiojn justify-content-end">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                Anterior
            </a>
        </li>
        {% endif %}
        <li class="page-item">
            <a class="pagae-link" href="#">
                {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
            </a>
        </li>
        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                Siguiente
            </a>
        </li>
        {% endif %}
    </ul>

</nav>