platzigram/urls.py
"""
Archivo de URLS de platzigram

"""

from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static  # para poder ver la foto del usuario
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),

 
    # Llama a posts/urls.py cuando se entra al home
    path('', include(('posts.urls','posts'), namespace='posts')),

    # Llama a users/urls.py cuando se entra al home/users/...
    path('users/', include(('users.urls', 'users'), namespace='users')),
    
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) #para mostrar la foto

#https://docs.djangoproject.com/en/2.2/ref/settings/

posts/urls.py
# Django
from django.urls import path

# Views
from posts import views

urlpatterns = [

   path(
       route='', 
       view=views.PostsFeedView.as_view(), 
       name='feed'
    ),

   path(
       route='posts/new/', 
       view=views.CreatePostView.as_view(),
       name='create'
    ),

    path(
        route='posts/<int:pk>/',
        view=views.PostDetailView.as_view(),
        name='detail'
    ),
]

users/urls.py
# URLS de usuarios

# Django
from django.urls import path
#https://docs.djangoproject.com/en/2.1/topics/class-based-views/#simple-usage-in-your-urlconf
#https://ccbv.co.uk/

# Views
from users import views

urlpatterns = [

    #Posts
    path(
        route='<str:username>/', #este es el kwarg (key word argument)
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # Administración
    path(
        route='login/', 
        view=views.login_view, 
        name='login'
    ),
    path(
        route='logout/', 
        view=views.logout_view, 
        name='logout'
    ),
    path(
        route='signup/', 
        view=views.signup, 
        name='signup'
    ),
    path(
        route='me/profile/', 
        view=views.update_profile, 
        name='update'
    )

]

users/models.py
#https://docs.djangoproject.com/en/2.2/topics/auth/customizing/

# Create your models here.

#Aca vamos a crear una tabla para los campos adicionales que Django no contiene # -*- coding: utf-8 -*-
#su tabla auth_user

from django.contrib.auth.models import User
from django.db import models

class Profile(models.Model):
#Modelo de perfil
#Modelo proxy que extiende la base de datos con otra info

#https://docs.djangoproject.com/en/2.2/ref/models/fields/
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200,blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateField(auto_now_add = True)
    modified = models.DateField(auto_now = True)

    def __str__(self):
        #Devuelve username
        return self.user.username

users/forms.py
# django
from django import forms

# models
from django.contrib.auth.models import User
from users.models import Profile

class SignUpForm (forms.Form):
    #Formujlario de registro
    username = forms.CharField(min_length=4, max_length=50)
    #https://docs.djangoproject.com/en/3.0/ref/forms/widgets/ para crear campos específicos
    password = forms.CharField(
        max_length=70,
        widget=forms.PasswordInput()
    )
    password_confirmation = forms.CharField(
        max_length=70, 
        widget=forms.PasswordInput()
    )
    first_name = forms.CharField(min_length=2, max_length=50)
    last_name = forms.CharField(min_length=2, max_length=50)

    email = forms.CharField(
        min_length=6,
        max_length=70,
        widget=forms.EmailInput()
    )

    # https://docs.djangoproject.com/en/3.0/ref/forms/validation/
    def clean_username(self):
        # nombre de usuario único, se hace a través de query
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()

        if username_taken:
            raise forms.ValidationError('Nombre de usuario en uso.')
        return username # ! Siempre se debe devolver el nombre de usuario

    def clean(self):
        #Verificación de confirmación de contraseña correcta
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no concuerdan')
        return data

    def save(self):
        #Crea usuario y lo guarda
        data = self.cleaned_data
        data.pop('password_confirmation')

        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()


# https://docs.djangoproject.com/en/3.0/ref/forms/fields/
class ProfileForm(forms.Form):
    # formulario de perfil

    website = forms.URLField(max_length=200, required=True)
    biography = forms.CharField(max_length=500, required=False)
    phone_number =forms.CharField(max_length=20, required=False)
    picture = forms.ImageField()

users/views.py
# https://docs.djangoproject.com/en/3.0/topics/auth/default/#auth-web-requests

from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
#para que no haga logout de una sesión inexistente se usa el decorador login_required
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import DetailView, TemplateView

#para registro de usuarios
#https://docs.djangoproject.com/en/2.2/topics/auth/default/

from users.models import Profile

#Excepciones
from django.db.utils import IntegrityError

# Models
from django.contrib.auth.models import User
from posts.models import Post

#Forms
from users.forms import ProfileForm, SignUpForm

# Create your views here.

# https://docs.djangoproject.com/en/2.2/topics/http/middleware/
# https://docs.djangoproject.com/en/2.2/topics/forms/
# https://docs.djangoproject.com/en/2.2/ref/forms/fields/


class UserDetailView(LoginRequiredMixin,DetailView):
    #Detalle de vista de usaurios

    template_name = 'users/detail.html'
    slug_field = 'username'
    slug_url_kwarg = 'username' # kwarg = key word argument. Del urls.py 
    queryset = User.objects.all()
    context_object_name = 'user'

    def get_context_data(self, **kwargs):
        #Añade post de usuarios al contexto
        #https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-display/#detailview
        context = super().get_context_data(**kwargs)
        user = self.get_object() #es el método que se encarga de hacer el queqry del object seguún los parámetros enviados
        #para mostrar los post del mismo usuario en orden ascendente
        context['posts'] = Post.objects.filter(user=user).order_by('-created') 
        return context

@login_required
def update_profile(request):

    profile = request.user.profile 

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            data = form.cleaned_data

            profile.website = data['website']
            profile.phone_number = data['phone_number']
            profile.biography = data['biography']
            profile.picture = data['picture']
            profile.save()
            #reverse construye una URL
            url = reverse('users:detail', kwargs={'username': request.user.username})
            return redirect(url) #el navegador siempre debe redireccionar a algún lado
    else:
        form = ProfileForm()


    return render(
        request = request,
        template_name = 'users/update_profile.html',
        context = {
            'profile': profile,
            'user': request.user,
            'form': form
        })


def login_view(request):
    
    if request.method == 'POST':

        username = request.POST['username']
        password = request.POST['password']

        user = authenticate(request, username=username, password=password)
        if user:
            login(request,user)
            # lo trae de users/urls.py
            return redirect('posts:feed')
        else:
            return render(request, 'users/login.html',{'error': 'Nombre de usuari o contraseña inválido'})

    return render(request, 'users/login.html')


# https://docs.djangoproject.com/en/2.2/topics/auth/default/
def signup(request):
    # Vista de sign up
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('users:login')
    else:
        form = SignUpForm()
    
    return render(
        request=request,
        template_name = 'users/signup.html',
        context={'form': form}
    )


@login_required
def logout_view(request):
    logout(request)
    return redirect('users:login')


"""
#! Método antiguo, ya se usa con class para no ver todo esto en el código
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        password_confirmation = request.POST['password_confirmation']

        if password != password_confirmation:
            return render(request,'users/signup.html', {'error': 'Password confirmation does not match'})
        
        try:
            user = User.objects.create_user(username=username, password=password)
        except IntegrityError:
            return render(request, 'users/signup.html', {'error': 'Username already in use'})

        user.first_name = request.POST['first_name']
        user.last_name = request.POST['last_name']
        user.email = request.POST['email']
        user.save()

        profile = Profile(user=user)
        profile.save()

        return redirect('login')


    return render(request, 'users/signup.html') 
"""

templates/users/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block head_content %}{% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" crossorigin="anonymous" />
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />

</head>

<body class="h-100">

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-sm-12 col-md-5 col-lg-5 pt-2 pl-5 pr-5 pb-5" id="auth-container">

                <img src="{% static "img/instagram.png" %}" class="img-fluid rounded mx-auto d-block pb-4"
                    style="max-width: 60%;">

                {% block container %}{% endblock%}

            </div>
        </div>
    </div>

</body>

</html>

templates/users/detail.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ user.username }} | Platzigram</title>
{% endblock %}

{% block container %}

<div class="container mb-5" style="margin-top: 8em;">
    <div class="row">
        <div class="col-sm-4 d-flex justify-content-center">
            <img src="{{ user.profile.picture.url }}" 
            alt="@{{ user.username}}" 
            class="rounded-circle"
            width="150px" />
        </div>
        <div class="col-sm-8">
            <h2 style="font-weight: 100;">
                {{ user.username }}
                {% if user == request.user %}
                <a href="{% url "users:update" %}" class="ml-5 btn btn-sm btn-outline-info">
                    Editar perfil
                </a>
                {% else %}
                <a href="" class="ml-5 btn btn-sm btn-primary">
                    Seguir
                </a>
                {% endif %}
            </h2>
            <div class="row mt-2" style="font-size: 1.2em">
                <div class="col-sm-4">
                    <b>{{ user.profile.posts_count }}785</b> posts
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.followers }}1,401</b> followers
                </div>
                <div class="col-sm-4">
                    <b>{{ user.profile.following }}491</b> following
                </div>
            </div>
            <div class="row mt-4">
                <div class="col-sm-12">
                    <p>{{ user.profile.biography }}</p>
                </div>
            </div>
        </div>
    </div>
</div>

<hr>

<div class="container" id="user-posts">
    <div class="row mt-3">
        {% for post in posts %}
        <div class="col-sm-4 pt-5 pb-5 pr-5 pl-5 d-flex justify-content-center align-items-center">
            <a href="" class="border">
                <img src="{{ post.photo.url }}" alt="{{ post.title }}" class="img-fluid" />
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

templates/users/login.html
{% extends "users/base.html" %}

{% block head_content %}
    <title>Platzigram Conéctate</title>
{% endblock %}


{% block container %}

    {% if error %}
        <p class="alert alert-danger">{{ error }}</p>
    {% endif %}

    <form method="POST" action="{% url "users:login" %}">


        {% csrf_token %}        
        
        <div class="form-grouop">
            <input class="form-control" type="text" placeholder="Username" name="username" />
        </div>

        <div class="form-grouop">
            <input class="form-control" type="password" placeholder="Password" name="password" />
        </div>
        
        <button class="btn btn-primary btn-block mt-5" type="submit">Conéctate!</button>
        
    </form>

    <p class="mt-4"> ¿No tienes cuenta? <a href="{% url "users:signup" %}">Regístrate acá</a></p>
    
    
{% endblock %}

<!--
    el action="{% url}" toma un nombre de URL (del url.py) y lo convierte a una URL normal
    {% csrf_token %} se usa para habilitar el login

    Para que el login sea obligatorio, en POST/views.py se pone el decorador "login_required"
-->

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Platzigram Registro</title>
{% endblock %}

{% block container %}

    <form action="{% url 'signup' %}" method="POST">
        {% csrf_token %}

        {{ form.as_p }}
    

        <button class="btn btn-primary btn-block mt-5" type="submit">Regístrate!</button>


    </form>

{% endblock %}

templates/users/update_profile.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}
<title>@{{ request.user.username }} | Update profile</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

                <!-- muestra los errrores del formulario en la parte de arriba. Se quita porque ya están 
                    abajo de cada campo marcado con rojo

                {% if form.errors %}
                <p class="alert alert-danger">{{ form.errors }}</p>
                {% endif %}
                -->

                <div class="media">
                    <!-- para mostrar la foto en preview -->
                    {% if profile.picture %}
                    <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                    {% else%}
                    <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                    {% endif %}

                    <div class="media-body">
                        <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                        <p class="ml-4"><input type="file" name="picture"></p>
                    </div>
                </div>

                {% for error in form.picture.errors %}
                    <div class="alert alert-danger">
                        <b>Picture: </b>{{error}}
                    </div>
                {% endfor %}

                <hr><br>
                <!--  Campos del website. El IF de la class es para colorear los errores y el IF
                del value es para que si hay error, no borre el valor digitado sino que lo siga mostrando-->
                <div class="form-group">
                    <label>Website</label>
                    <input 
                        class="form-control {% if form.website.errors %} is-invalid{% endif %}" 
                        type="text" 
                        name="website" 
                        placeholder="Website"
                        value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}" 
                    />
                    <!-- Para mostrar el error debajo del campo marcado -->
                    <div class="invalid-feedback">
                        {% for error in form.website.errors %}
                            {{ error }}
                        {% endfor %}
                    </div>
                </div>

                <!--  Campos del Biography. El IF de la class es para colorear los errores y el IF
                del value es para que si hay error, no borre el valor digitado sino que lo siga mostrando-->
                <div class="form-group">
                    <label>Biography</label>
                    <textarea 
                        class="form-control {% if form.biography.errors %} is-invalid{% endif %}" 
                        name="biography"
                        >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                    <!-- Para mostrar el error debajo del campo marcado -->
                    <div class="invalid-feedback">
                        {% for error in form.biography.errors %}{{ error }}{% endfor %}
                    </div>
                </div>

                <!--  Campos del Phone_number. El IF de la class es para colorear los errores y el IF
                del value es para que si hay error, no borre el valor digitado sino que lo siga mostrando-->
                <div class="form-group">
                    <label>Phone number</label>
                    <input 
                        class="form-control {% if form.phone_number.errors %} is-invalid{% endif %}" 
                        type="text" 
                        name="phone_number" 
                        placeholder="Phone number"
                        value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}" 
                    />
                    <!-- Para mostrar el error debajo del campo marcado -->
                    <div class="invalid-feedback">
                        {% for error in form.phone_number.errors %}{{ error }}{% endfor %}
                    </div>
                </div>

                <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/users/update_profile2.html
{% extends "base.html" %}

{% block head_content %}
<title>@{{ request.user.username }} | Update Profile </title>
{% endblock %}

{% block container %}
    <h1 class="mt-5">
        @ {{ request.user.username}}
    </h1>
{% endblock %}